### ISSUE TITLE
Add `In-Reply-To` header in replies to subscribe or unsubscribe

### ISSUE THREAD

**Issue by n-peugnet** [club-1/newsletter#1]
For this we need to read the `Message-ID` header of the mail we are replying to.

Later it would be interesting to also add the `References` header. But it would be more complicated.

See https://www.ietf.org/rfc/rfc2822.html#section-3.6.4

> The "In-Reply-To:" field will contain the contents of the "Message-ID:" field of the message to which this one is a reply (the "parent message").

> The "References:" field will contain the contents of the parent's "References:" field (if any) followed by the contents of the parent's "Message-ID:" field (if any).  If the parent message does not contain a "References:" field but does have an "In-Reply-To:" field containing a single message identifier, then the "References:" field will contain the contents of the parent's "In-Reply-To:" field followed by the contents of the parent's "Message-ID:" field (if any).  If the parent has none of the "References:", "In-Reply-To:", or "Message-ID:" fields, then the new message will have no "References:" field.

**Comment by vincent-peugnet** [comment]
closed by 1c6324decefa8bd88f006ad8bdd99128af353492
